<?xml version="1.0"?>
<package format="2">
  <name>diff_tracked_planning</name>
  <version>0.1.0</version>
  <description>Fields2Cover coverage planning for the tracked robot.</description>

  <license>TODO</license>
  <maintainer email="nhy@163.com">democles</maintainer>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>nav_msgs</depend>
  <depend>roscpp</depend>

  <export/>
</package>
